title: Digitales Handwerkszeug für Bibliothekar:innen - Ein Lerntagebuch
author: Alisa Person
info: Bibliotheks- und Informationsmanagement
description: > # this means to ignore newlines until "baseurl:"
  Lerntagebuch zum Wahlkurs "Digitales Handwerkszeug für Bibliothekar:innen" an der HAW Hamburg

# social links
twitter_username: alisa_per # DO NOT include the @ character, or else the build will fail!
github_username: alisa-person # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
